---
- name: Install Rust and Cargo
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "$HOME/.cargo/bin/rustc"

- name: Add Rust to PATH in .bashrc
  lineinfile:
    path: "~/.bashrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present
    create: yes
