---
- name: Install dependencies on server
  hosts: all
  become: yes
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io]
        state: present
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install Rust and Cargo
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "$HOME/.cargo/bin/rustc"

    - name: Add Rust to PATH in .bashrc
      lineinfile:
        path: "~/.bashrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        state: present
        create: yes

    - name: Install Java
      apt:
        name: default-jre
        state: present

    - name: Install Minikube
      shell: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
