---
- name: Set up server environment
  hosts: all
  become: true
  tasks:
    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
      changed_when: false
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      register: hostname_result
    - name: Update /etc/hostname
      lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}"
      when: hostname_result.changed
    - name: Reboot server
      command: shutdown -r +1 "Rebooting server for hostname change"
      async: 0
      poll: 0
      ignore_errors: true
